[tools]
atuin = "latest"
fd = "latest"
helix = "latest"
rg = "latest"
rust = "latest"
zoxide = "latest"
yazi = "latest"
fzf = "latest"
carapace = "latest"
cargo-binstall = "latest"
"cargo:nu" = "latest"
"cargo:ouch" = "latest"
go = "latest"
github-cli = "latest"
"cargo:tlrc" = "latest"
uv = "latest"
"github:tombi-toml/tombi" = "latest"
biome = "latest"
